# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build (and Release)

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: compileProductionExecutableKotlinJs
      - name: Tar Artifact
        run: tar -czf ParkingLot-LLD-Kotlin-MPP.nodejs.tgz build/js/packages/ParkingLot-LLD-Kotlin-MPP
      - name: Upload JS Build
        uses: actions/upload-artifact@v2
        with:
          name: js-build
          path: ParkingLot-LLD-Kotlin-MPP.nodejs.tgz

  build_jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleDist
      - name: Upload JVM Build
        uses: actions/upload-artifact@v2
        with:
          name: jvm-build
          path: build/distributions/ParkingLot-LLD-Kotlin-MPP-*.zip

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: macosX64Binaries
      - name: Upload MacOS Build
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: build/bin/macosX64/releaseExecutable/ParkingLot-LLD-Kotlin-MPP.kexe

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: linuxX64Binaries
      - name: Upload Linux Build
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build/bin/linuxX64/releaseExecutable/ParkingLot-LLD-Kotlin-MPP.kexe

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: mingwX64Binaries
      - name: Upload Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/bin/mingwX64/releaseExecutable/ParkingLot-LLD-Kotlin-MPP.exe

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - "build_js"
      - "build_jvm"
      - "build_macos"
      - "build_linux"
      - "build_windows"
    runs-on: ubuntu-latest
    steps:
      - name: Download Builds
        uses: actions/download-artifact@v3
        with:
          path: build
      - name: Rename Releases
        run: |
          mv build/linux-build/ParkingLot-LLD-Kotlin-MPP.kexe build/linux-build/ParkingLot-LLD-Kotlin-MPP.linux.bin
          mv build/macos-build/ParkingLot-LLD-Kotlin-MPP.kexe build/macos-build/ParkingLot-LLD-Kotlin-MPP.macos.bin
      - name: Make Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/linux-build/ParkingLot-LLD-Kotlin-MPP.linux.bin
            build/macos-build/ParkingLot-LLD-Kotlin-MPP.macos.bin
            build/windows-build/ParkingLot-LLD-Kotlin-MPP.exe
            build/jvm-build/ParkingLot-LLD-Kotlin-MPP-*.zip
            build/js-build/ParkingLot-LLD-Kotlin-MPP.nodejs.tgz
