name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: jsTest
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            build/test-results/jsNodeTest
            build/reports/tests/jsTest
  test_jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: jvmTest
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            build/test-results/jvmTest
            build/reports/tests/jvmTest